apiVersion: v1
kind: Namespace
metadata:
  name: observability-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-demo
  namespace: observability-demo
  labels:
    app: observability-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: observability-demo
  template:
    metadata:
      labels:
        app: observability-demo
    spec:
      containers:
      - name: observability-demo
        image: virtualthoughts/observability-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: observability-demo
  namespace: observability-demo
  labels:
    app: observability-demo
spec:
  selector:
    app: observability-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-demo
  namespace: observability-demo
  labels:
    app: observability-demo
spec:
  selector:
    matchLabels:
      app: observability-demo
  endpoints:
  - port: metrics
    interval: 5s
